### ISSUE TITLE
Write some tests for `Core.update`

### ISSUE THREAD

**Issue by alpacaaa** [alpacaaa/tex#1]
Most of the business logic is inside that function, would be good to have some basic tests to check if it works right.

**Comment by sphaso** [comment]
Absolutely! I'll start on my own and see how it goes first, as I won't be
able to pair much this week (I'll be at munihac).

**Comment by sphaso** [comment]
Sorry for the terrible delay, I finally implemented a small test for one `update` `Cmd` (namely `JumpNext`). Let me know if you like the style and I'll write more :)
https://github.com/alpacaaa/lame-fs/commit/4611d87379e73be42c3b40206ebb63faecc8a195

**Comment by alpacaaa** [comment]
This is great, keep them coming! Thank you :)

**Comment by sphaso** [comment]
@alpacaaa I added more tests but:
- `JumpParentFolder` is not working as I had expected. If currentFolder is, say, "/a/b" I expected to get "/a" after running that command. Is my understanding wrong?
- `JumpHomeDirectory` seem to read from the actual filesystem. To test it then, I guess I need to create a mock monad and give it an instance of `FileSystem`. Is this correct?

**Comment by alpacaaa** [comment]
I guess the answer to both questions is that we want to provide a mock instance for the `FileSystem` class. That means I wouldn't use `App` in tests because, as you've pointed out, it hits the underlying filesystem making things hard to test.

What we want I think is a `TestApp` type that provides a very dumb instance for `FileSystem`. It could still run in `IO` as in `newtype TestApp a = TestApp (IO a)` so that we can use a simple `IORef` to keep track of the current directory and stuff like that.

Or maybe we don't even need that, as `scanDirectory` gets a directory as input. Not sure if we'd need `IO` for anything else, but we can "upgrade" the type later if needed. For now a simple `newtype TestApp = TestApp a` could very well be all we need.

Thanks for working on this! :)

**Comment by sphaso** [comment]
My pleasure!
I've pushed the dummy monad. It was much much easier than I thought except... it's working the way I supposed it would :D the tests are still red. I'll hit my head on it a bit more

**Comment by alpacaaa** [comment]
Dummy monad looking great! :D Let me know if you need help fixing the red tests.

**Comment by sphaso** [comment]
I finished the tests for `update`. Regarding the broken test, I'm not so sure one can use `PointedList.moveTo` with negative indeces:
```
> let (Just filez) = Data.List.PointedList.fromList [ Core.File "a" Core.NormalFile, Core.File "b" Core.NormalFile ]
> Data.List.PointedList.moveN (-1) filez
Nothing
```

**Comment by alpacaaa** [comment]
@sphaso Fixed the broken search test, and all tests are passing now 😍. Feel free to close this issue if you feel like we have enough tests!
